title: Tri Nguyen - Xamarin cross-platform developer
description: > # this means to ignore newlines until "baseurl:"
  Software development blog written by a Xamarin cross-platform developer
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://trinnguyen.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tri Nguyen # add your name
author-img: trinnguyen.jpg # add your photo
about-author: Mobile developer specializes in Xamarin and .Net. Interested in programming languages and compilers.
social-cv: https://stackoverflow.com/users/1690138/tri-nguyen
social-twitter:  # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: trinnguyen # add your Github handle
social-linkedin: trinnguyen # add your Linkedin handle
social-email:  # add your Email address

# Disqus
discus-identifier: trinnguyen # add your discus identifier

# Tracker
analytics: # Google Analytics
mixpanel-code: 187cb6ebfb193858c660440e4ac58062 # Mixpanel

# Build Settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "vendor"]
